# Generated by Django 5.0.6 on 2024-06-29 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('complete_date', models.DateTimeField(blank=True, null=True)),
                ('pay_method', models.IntegerField(choices=[(1, 'Cash'), (2, 'Online')], default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='user.customer')),
                ('products', models.ManyToManyField(related_name='orders', to='product.product')),
            ],
        ),
    ]
